//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group6_iCAREAPP.Models
{
    using System;
    using System.Collections.Generic;

    // Class representing a drug entry in the drugs dictionary
    public partial class DrugsDictionary
    {
        public string drugID { get; set; } // Unique identifier for the drug
        public string drugName { get; set; } // Name of the drug
    }
}
